apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: window-cluster
  region: us-east-1
  version: "1.28"

KubernetesNetworkConfig:
  IpFamily: ipv4

managedNodeGroups:
  - name: test-group
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 40
    # privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
    tags:
      kubernetes.io/cluster/yogesh-cluster: owned
      environment: production
    ssh:
      allow: false
    labels:
      role: worker