apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-eks-pipeline-deployment
  labels:
    app: my-eks-pipeline-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-eks-pipeline-deployment
  template:
    metadata:
      labels:
        app: my-eks-pipeline-deployment
    spec:
      containers:
        - name: my-eks-pipeline-deployment
          image: 040112606736.dkr.ecr.us-east-1.amazonaws.com/docker-registry:2024-03-12.10.09.22.7b89ffee
          ports:
            - containerPort: 80