apiVersion: v1
kind: Service
metadata:
  name: my-eks-pipeline-deployment
spec:
  selector:
    app: my-eks-pipeline-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 31100
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-eks-pipeline-deployment
  labels:
    app: my-eks-pipeline-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-eks-pipeline-deployment
  template:
    metadata:
      labels:
        app: my-eks-pipeline-deployment
    spec:
      containers:
        - name: my-eks-pipeline-deployment
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 80